name: flutter_shoppinglist
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  google_sign_in: ^4.5.6
  flutter_signin_button: ^1.1.0
  rive: ^0.6.5
  flutter_bloc: ^6.1.1
  provider: ^4.3.2+3
  equatable: ^1.2.5
  pedantic: ^1.9.2
  formz: ^0.3.2
  jiffy: ^3.0.1
  animations: ^1.1.2
  shared_preferences: ^0.5.12+4
  shrink_sidemenu: ^1.0.0+3
  flutter_search_bar: ^2.1.0
  splashscreen: ^1.3.5
  flutter_statusbarcolor: ^0.2.3
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  flutter_native_splash: ^0.2.9

flutter_native_splash:
  color: "#fafafa"
  color_dark: "#303030"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
